package com.softserve.enums;

public enum FieldType {
    ENTITY_CREATED_DATE,
    AUTHOR_FIRST_NAME,
    AUTHOR_SECOND_NAME,
    BOOK_NAME,
    BOOK_YEAR_PUBLISHER,
    BOOK_ISBN,
    BOOK_PUBLISHER,
    BOOK_RATING,
    REVIEW_COMMENTER_NAME,
    REVIEW_COMMENT,
    REVIEW_RATING
}
