export enum FieldTypeEnum {
  ENTITY_CREATED_DATE = "ENTITY_CREATED_DATE",
  AUTHOR_ID = "AUTHOR_ID",
  AUTHOR_FIRST_NAME = "AUTHOR_FIRST_NAME",
  AUTHOR_SECOND_NAME = "AUTHOR_SECOND_NAME" ,
  BOOK_ID = "BOOK_ID",
  BOOK_NAME = "BOOK_NAME",
  BOOK_YEAR_PUBLISHER= "BOOK_YEAR_PUBLISHER",
  BOOK_ISBN = "BOOK_ISBN",
  BOOK_PUBLISHER= "BOOK_PUBLISHER",
  RATING = "RATING",
  REVIEW_ID = "REVIEW_ID",
  REVIEW_COMMENTER_NAME = "REVIEW_COMMENTER_NAME",
  REVIEW_COMMENT = "REVIEW_COMMENT",
  REVIEW_RATING = "REVIEW_RATING"

}
export const FieldType2LabelMapping: Record<FieldTypeEnum, string> = {
  [FieldTypeEnum.ENTITY_CREATED_DATE]: "ENTITY CREATED DATE",
  [FieldTypeEnum.AUTHOR_ID]: "AUTHOR ID",
  [FieldTypeEnum.AUTHOR_FIRST_NAME]: "AUTHOR FIRST NAME",
  [FieldTypeEnum.AUTHOR_SECOND_NAME]: "AUTHOR SECOND NAME",
  [FieldTypeEnum.BOOK_ID]: "BOOK ID",
  [FieldTypeEnum.BOOK_NAME]: "BOOK NAME",
  [FieldTypeEnum.BOOK_YEAR_PUBLISHER]: "BOOK YEAR PUBLISHER",
  [FieldTypeEnum.BOOK_ISBN]: "BOOK ISBN",
  [FieldTypeEnum.BOOK_PUBLISHER]: "BOOK PUBLISHER",
  [FieldTypeEnum.RATING]: "RATING",
  [FieldTypeEnum.REVIEW_ID]: "REVIEW ID",
  [FieldTypeEnum.REVIEW_COMMENTER_NAME]: "REVIEW COMMENTER NAME",
  [FieldTypeEnum.REVIEW_COMMENT]: "REVIEW COMMENT",
  [FieldTypeEnum.REVIEW_RATING]: "REVIEW RATING",
};
